#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/dns-flood-detector" ]; then
	if [ ! -e "/etc/init/dns-flood-detector.conf" ]; then
		update-rc.d dns-flood-detector defaults 40 >/dev/null
	fi
	invoke-rc.d dns-flood-detector start || exit $?
fi
# End automatically added section
